package.json, src/app.module.ts, src/chapters/chapters.module.ts, src/chapters/entities/chapter.entity.ts, src/config/typeorm.config.ts, src/config/validationSchema.ts, src/learnings/entities/learning.entity.ts, src/learnings/learnings.module.ts, src/problems/entities/problem.entity.ts, src/problems/problems.module.ts, src/users/entities/users.entity.ts, src/users/users.module.ts, yarn.lock
=> Feature/#2 초기 Entity 작성

package.json, src/auth/auth.service.ts, src/common/dtos/Response.dto.ts, src/users/dtos/delete-account.dto.ts, src/users/dtos/modify-password.dto.ts, src/users/dtos/profile.dto.ts, src/users/users.controller.ts, src/users/users.module.ts, src/users/users.service.ts, yarn.lock
| URL                | method | Usage                | Authorization Needed |
| ------------------ | ------ | -------------------- | -------------------- |
| /users         | DELETE  | 회원 탈퇴      | O                    |
| /users/password | PATCH   | 비밀번호 변경      | X                    |
기능 명세서도 업데이트했습니다!
@Dh3356 확인하시면  
제가 작업하면서 response에 statuscode가 모두 들어가도록 하면 좋을 것 같아서  
CoreRes 파일하나 생성했는데 response dto가 모두 이걸 상속받고  
리턴 데이터에 statusCode가 포함되도록 수정 작업해주실 수 있을까요?
=> Feature/#6 user domain 작업

src/learnings/dtos/chapters.dto.ts, src/learnings/dtos/progress.dto.ts, src/learnings/learnings.controller.ts, src/learnings/learnings.module.ts, src/learnings/learnings.service.ts
Learning domain api 작업
| URL                | method | Usage                | Authorization Needed |
| ------------------ | ------ | -------------------- | -------------------- |
| /learnings/progress?type={type}          | GET  | 진도율      | O                    |
| /learnings//chapters?type={type} | GET   | 목차      | O                    |
learning, chapter 데이터 mocking하여 진행함
Closes #14
=> Feat/#14 learning domain 작업

src/learnings/learnings.service.ts, yarn.lock
response의 chapter object에 isCompleted property 추가
`Before`
```json
{
"statusCode": 200,
"message": "Chapters successfully retrieved",
"chapters": [
{
"id": "4d34615a-50be-4dac-9a76-1558d749bde8",
"title": "챕터 1",
"help_message": "blah"
},
{
"id": "b18b3b5b-4dbc-4a9a-89d6-4e61aa4ceb2c",
"title": "챕터 2",
"help_message": null
}
]
}
```
`After`
```json
{
"statusCode": 200,
"message": "Chapters successfully retrieved",
"chapters": [
{
"id": "4d34615a-50be-4dac-9a76-1558d749bde8",
"title": "챕터 1",
"help_message": null,
"isCompleted": true
},
{
"id": "b18b3b5b-4dbc-4a9a-89d6-4e61aa4ceb2c",
"title": "챕터 2",
"help_message": null,
"isCompleted": false
}
]
}
```
Closes #22
=> Feature/#22 getChapters method 반환값에 챕터별 완료 여부 추가

src/chapters/entities/chapter.entity.ts, src/learnings/entities/learning.entity.ts, src/problems/entities/problem.entity.ts, src/users/entities/users.entity.ts
@PrimaryGeneratedColumn('uuid') 인 id 컬럼의 타입이 number로 되어 있음
Closes #25
=> Feature/#25 entity id컬럼 타입 수정

src/problems/entities/problem.entity.ts
예시 문제를 없애기로 결정함에 따라 Problem table schema 변경
- Problem Entity의 is_example 제거
Closes #24
=> Feature/#24 예시 문제 제거

src/chapters/chapters.controller.ts, src/chapters/chapters.module.ts, src/chapters/chapters.service.ts, src/chapters/dtos/chapter.dto.ts, src/problems/entities/problem.entity.ts, src/problems/utils/problem.util.ts
해당 챕터 내의 시나리오, 문제, 도움말 전부 조회
| URL                | method | Usage                | Authorization Needed |
| ------------------ | ------ | -------------------- | -------------------- |
| /chapters/{id}          | GET  | 해당 챕터 정보 조회      | O                    |
Closes #31
=> Feature/#31 챕터 정보 api 구현

src/chapters/chapters.service.ts, src/chapters/entities/chapter.entity.ts, src/learnings/learnings.service.ts, src/users/entities/users.entity.ts
Entity property naming 수정
- Snake_Case에서 camelCase로 변경
Closes #38
=> Feature/#38 Entity property naming 수정, 이에 따른 코드 리팩터링

src/chapters/chapters.service.ts, src/problems/problems.service.ts
answerOptions가 null인 문제를 불러올 때 Exception 발생, validation 추가
Closes #43
=> !HOTFIX/#43 answerOptions validation 추가

src/problems/problems.service.ts
problem을 create할 때 발생하는 오류 메시지 수정
dto에 chapterId를 받는데, 해당 chapter가 없을 때 발생하는 message가 'Problem dose not exist 였음'
'Chapter does not exist'로 수정
Closes #45
=> !HOTFIX/#45 problem Create 시 발생하는 오류 메시지 수정

src/chapters/chapters.service.ts
chapterService getChapter() 잘못된 조건문 수정
Closes #47
=> !HOTFIX/ #47 chapterService getChapter() 잘못된 조건문 수정

package.json, src/apis/openai/openai.module.ts, src/apis/openai/openai.service.ts, src/apis/openai/throttler-behind-proxy.guard.ts, yarn.lock
악의적 openAI 요청 제한을 위한 Rate Limiting 구현
Closes #49
=> Feature/#49 openAI 요청 제한을 위한 Rate Limiting 구현

src/chapters/chapters.module.ts, src/chapters/chapters.service.ts, src/users/entities/users.entity.ts
각 챕터마다 푼 문제를 제외한 나머지 중 랜덤하게 3문제를 반환해야함.
Closes #37
=> Feature/#37 랜덤하게 3문제 반환 구현

src/auth/jwt/jwt.strategy.ts, src/problems/problems.service.ts
=> Feature/#57 모든 예외를 적절한 예외로 수정

src/auth/auth.service.ts, src/auth/dtos/login-response.dto.ts
login response data에 nickName 추가
Closes #62
=> Feature/#62 login response data에 nickName 추가

src/auth/auth.service.ts
cookie에 domain 옵션 추가
cookie 옵션 추가
Closes #66
=> Feature/#66 response의 cookie에 domain 추가

src/auth/auth.service.ts, src/auth/jwt/jwt.strategy.ts, src/main.ts
set cookie를 위한 credentials 옵션 추가
- app.enableCors({origin: true,credentials: true}); 추가
Closes #69
=> !HOTFIX/#69 set-cookie 동작을 위한 추가 설정

src/chapters/chapters.service.ts, src/chapters/dtos/crud/create/create.dto.ts, src/chapters/dtos/crud/update/update.dto.ts
crud api에 order 추가사항 반영
- chapter domain
- dtos
- service
=> !Hotfix/#76 chapter crud api에 order 반영

src/problems/dtos/submit-response.dto.ts, src/problems/dtos/submit.dto.ts, src/problems/problems.service.ts
=> Feature/#74 채점 로직 수정

src/apis/openai/openai.service.ts
openAI 질문 방식 수정
기존에 주관식, 빈칸채우기 답 제출 시, 띄어쓰기에 문제가 없으면 원래의 문자열을 반환하는 게 아닌 다른 문장을 반환하던 문제가 있었음.
질문 방식 수정, lowerCase 적용을 통해 원본 문자열을 반환하도록 수정
Closes #81
=> Feature/#81 openAI 질문 방식 수정

src/chapters/chapters.service.ts
chapter 조회 시 문제 완료 여부와 관계없이 반환하도록 수정
문제 완료 여부와 관계없이 해당 chapter의 모든 문제 중 3개를 랜덤으로 반환
Closes #78
=> Feature/#78 chapter 조회 시 문제 완료 여부와 관계없이 반환하도록 수정

src/apis/openai/openai.service.ts, src/problems/problems.service.ts
채점 로직 추가, openAI 질문 방식 미세 조정
특정 질문에 대해 답을 정확하게 return하지 않는 이슈가 있었음, 해당 이슈를 해결하기 위한 작업
=> Feature/#84 채점 로직 추가, openAI 질문 방식 미세 조정

src/auth/auth.controller.ts, src/auth/auth.service.ts, src/auth/dtos/logout-response.dto.ts
cookie를 사용하기로 결정함에 따라 logout api가 필요함
| URL                | method | Usage                | Authorization Needed |
| ------------------ | ------ | -------------------- | -------------------- |
| /auth/logout      | POST| 로그아웃      | O                    |
Closes #79
=> Feature/#79 logout api 추가 구현

src/problems/problems.service.ts
채점 시 대문자를 소문자로 바꿔 채점하는 코드 추가
현재 사용자가 입력한 답은 소문자로 바꾸어 채점 중인데 문제 정답이 대문자가 되는 상황에 따른 수정
Closes #91
=> Feature/#91 채점 로직 추가 수정

src/users/dtos/modify-password.dto.ts, src/users/users.service.ts
=> Feature/#89 password 변경 시 validation 추가

src/users/users.service.ts
password 변경 로직 수정
잘못된 코드로 인한 오류 발견
=> Feature/#96 password 변경 로직 수정

src/users/users.controller.ts
필요 없는 console.log 삭제
Closes #98
=> Feature/#98 필요 없는 console.log 삭제

src/app.module.ts
ThrottlerBehindProxyGuard를 사용하도록 수정
기존에 proxy를 대비해 만들어 놓은 ThrottlerBehindProxyGuard를 실제로 사용하지 않는 것을 발견
사용하도록 수정
Closes #100
=> Feature/#100 ThrottlerBehindProxyGuard를 사용하도록 수정

src/main.ts
Trust Proxy 설정
Trust Proxy 설정을 통해 Proxy를 통해서도 동작하도록 설정
=> Feature/#102 Trust Proxy 설정

src/learnings/learnings.service.ts
진도율이 완료한 문제 수에 따라 책정되고 있었음
완료한 챕터를 기준으로 진도율을 반영하도록 진도율 계산 로직 수정
Closes #104
=> Feature/#104 진도율 계산 로직 수정

src/learnings/learnings.service.ts, src/problems/problems.service.ts
git 사용 미숙으로 인한 잘못된 revert 되돌리기
Closes #110
=> Hotfix/#110 잘못된 revert 수정

src/users/users.controller.ts, src/users/users.service.ts
회원 탈퇴시 cookie의 jwt 제거
회원 탈퇴시 cookie의 jwt 제거
Closes #113
=> Feature/#113 회원 탈퇴시 cookie의 jwt 제거

src/config/typeorm.config.ts
typeorm synchronize false로 변경
typeorm synchronize false로 변경
Closes #119
=> Feature/#119 typeorm synchronize false로 변경

src/chapters/chapters.controller.ts, src/learnings/learnings.controller.ts, src/problems/problems.controller.ts
CRUD API ADMIN만 사용할 수 있도록 변경
Closes #121
=> Feature/#121 CRUD API ADMIN만 사용할 수 있도록 변경
